packages:
  # Applications
  - 'apps/*'
  # Shared packages and libraries
  - 'packages/*'
  - 'libs/*'

  # Exclude test directories and dist folders
  - '!**/dist'
  - '!**/node_modules'
  - '!**/*.test.*'
